import { jsPDF } from "jspdf";
import { RecommendedCollege, StudentProfile } from "@/lib/types";

export function generatePDF(
  recommendations: RecommendedCollege[],
  profile: StudentProfile
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Title ──
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("EduCompass AI — College Report", pageWidth / 2, y, {
    align: "center",
  });

  y += 10;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text("Personalised college recommendations based on your profile", pageWidth / 2, y, {
    align: "center",
  });

  y += 6;
  doc.text(
    "⚠️ Sample data for demo purposes — not for real admission decisions",
    pageWidth / 2,
    y,
    { align: "center" }
  );

  // ── Profile Summary ──
  y += 14;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Student Profile", 14, y);

  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const advRankStr = profile.jeeAdvancedRank ? `#${profile.jeeAdvancedRank}` : "N/A";
  const profileLines = [
    `JEE Main Rank: #${profile.jeeMainRank}  |  JEE Adv Rank: ${advRankStr}  |  Cat: ${profile.category.toUpperCase()}`,
    `Home State: ${profile.homeState}  |  Budget: INR ${(profile.budget / 100000).toFixed(1)} Lakhs`,
    `Hostel Needed: ${profile.hostelNeeded ? "Yes" : "No"}  |  Career Goal: ${profile.careerGoal.replace(/_/g, " ")}`,
    `Preferred Branches: ${profile.preferredBranches.length > 0 ? profile.preferredBranches.join(", ") : "Any"}`,
  ];

  for (const line of profileLines) {
    doc.text(line, 14, y);
    y += 6;
  }

  // ── Divider ──
  y += 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;

  // ── Recommendations ──
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Top ${Math.min(recommendations.length, 10)} Recommendations`, 14, y);
  y += 10;

  for (let i = 0; i < Math.min(recommendations.length, 10); i++) {
    const rec = recommendations[i];

    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // College header
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(80, 60, 160); // Violet-ish
    doc.text(`#${i + 1}  ${rec.college.name}`, 14, y);

    y += 6;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(
      `${rec.college.type} | ${rec.college.city}, ${rec.college.state} | Branch: ${rec.matchedBranch.name}`,
      14,
      y
    );

    y += 5;
    doc.text(
      `FIT Score: ${Math.round(rec.overallScore)}/100  |  Fees: INR ${(rec.college.fees / 100000).toFixed(1)}L  |  Avg Pkg: INR ${rec.college.avgPackageLPA} LPA`,
      14,
      y
    );

    y += 5;
    const breakdownStr = `Safety: ${Math.round(rec.breakdown.admissionSafety)}  |  ROI: ${Math.round(rec.breakdown.roi)}  |  Branch: ${Math.round(rec.breakdown.branchMatch)}  |  Placement: ${Math.round(rec.breakdown.placement)}  |  Hostel: ${Math.round(rec.breakdown.hostel)}  |  Coding: ${Math.round(rec.breakdown.codingCulture)}`;
    doc.setTextColor(100, 100, 100);
    doc.text(`Scores: ${breakdownStr}`, 14, y);

    // Top reasons
    if (rec.topReasons.length > 0) {
      y += 5;
      doc.setTextColor(60, 120, 60);
      for (const reason of rec.topReasons) {
        doc.text(`✓ ${reason}`, 18, y);
        y += 4.5;
      }
    }

    y += 6;
    doc.setDrawColor(230, 230, 230);
    doc.line(14, y, pageWidth - 14, y);
    y += 6;
  }

  // ── Footer ──
  y += 4;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by EduCompass AI on ${new Date().toLocaleDateString("en-IN")}`,
    pageWidth / 2,
    y,
    { align: "center" }
  );

  doc.save("EduCompass_AI_Report.pdf");
}
